segona pujada
apertium/apertium-oci-fra pull request #3
Opened 2018-03-22 21:56 UTC by Capsot

2018-03-22 22:36 UTC, xavivars requested changes
Cal anar amb compte amb les variants. Els canvis que eliminen informació de variants han de fer-se amb compte.

2018-03-22 22:36 UTC, xavivars commented on apertium-oci-fra.oci-fra.dix
> +     <e><p><l>nosautres<s n="prn"/><s n="tn"/><s n="p1"/></l><r>nous<s n="prn"/><s n="tn"/><s n="p1"/></r></p><par n="GD_mf"/></e>
el mateix comentari que dalt

2018-03-22 22:36 UTC, xavivars commented on apertium-oci-fra.oci-fra.dix
> +     <e><p><l>ieu<s n="prn"/><s n="tn"/><s n="p1"/></l><r>je<s n="prn"/><s n="tn"/><s n="p1"/></r></p></e>
aquest canvi no és correcte, ja que ara, per a la variant `oci@gascon`, hi ha dues traduccions vàlides quan es tradueix del francés `je<s n="prn"/><s n="tn"/><s n="p1"/>`. S'hauria de recuperar `alt="oci"`

2018-03-22 22:53 UTC, Capsot commented on apertium-oci-fra.oci-fra.dix
> +     <e><p><l>nosautres<s n="prn"/><s n="tn"/><s n="p1"/></l><r>nous<s n="prn"/><s n="tn"/><s n="p1"/></r></p><par n="GD_mf"/></e>
Bona nit i gràcies. Pensava que com que la varietat usual que usàvem era l'occità "estàndard" no feia falta aquesta marca.

2018-03-22 22:53 UTC, Capsot commented on apertium-oci-fra.oci-fra.dix
> +     <e><p><l>ieu<s n="prn"/><s n="tn"/><s n="p1"/></l><r>je<s n="prn"/><s n="tn"/><s n="p1"/></r></p></e>
Ja. Gràcies, crec que ho he entés. Quan passa del francès al gascó només tria si l'altra etiqueta no és genèrica (doncs no tria sistemàticament a oci@gascon). Pensava que reconeixia l'etiqueta sistemàticament però es veu que no. Llavors s'haurà d'anar en compte amb tota la variació. Ho hauré de pensar millor. Bona nit!

2018-03-22 22:54 UTC, Capsot commented on apertium-oci-fra.oci-fra.dix
> +     <e><p><l>ieu<s n="prn"/><s n="tn"/><s n="p1"/></l><r>je<s n="prn"/><s n="tn"/><s n="p1"/></r></p></e>
PS: De fet, m'ho he de mirar tot amb molta cura, ja que hi ha "massa" variació.

2018-03-23 19:11 UTC, hectoralos approved these changes

2018-03-23 19:16 UTC, merged